### ISSUE TITLE
Missing random baseline

### ISSUE THREAD

**Issue by arianpasquali** [smartschat/tilse#1] opened 2020-01-31 10:38 UTC
Hi Sebastian. First of all congrats for the nice piece of work.
The metrics and the submodular approaches looks really good.
I reproduced the paper's results and I get similar scores, however the random baseline is missing in the code. Maybe just forgot to commit.

https://github.com/smartschat/tilse/blob/f5f2b9afc1e6969c041ca3753b68c657fa46b30c/bin/predict-timelines#L80

best

**Comment by MorenoLaQuatra** [comment] 2020-03-19 17:12
I agree with Arian, excellent work both for predicting and evaluation timeline data.
 
Unfortunately I encountered some problems in reproducing paper results. Can @arianpasquali  share the steps performed to reproduce results? I tried using the `get-and-preprocess-data` and `predict-timelines` in `bin` folder (updating accordigly the config files with new data directories), did you try the same?

**Comment by smartschat** [comment] 2020-03-19 19:48
Thank you for the interest in my work! I re-added the random baseline with commit fbbb409. 

I'm leaving the issue open because of Moreno's problems -- please let me know if I can be of any help. By running the two scripts you should be able to produce results very similar to the results in the paper (there will be slight differences since I fixed a few minor bugs; and changes/updates to preprocessing libraries may also affect the results to some minor extent).

**Comment by MorenoLaQuatra** [comment] 2020-03-20 08:48
Thanks for the quick answer Sebastian. 

Actually I'm not sure if some of my errors are due to preprocessing or prediction. Lunching `get-and-preprocess-data` I got some Warning but the data are still there. So I proceed with predictions, and for adapted submodular I got the following kind of error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-2c048e73567e> in <module>
     55     start_time = timeit.default_timer()
     56 
---> 57     returned_timelines = algorithm.run(news_corpora, reference_timelines)
     58 
     59     elapsed = timeit.default_timer() - start_time

<ipython-input-3-7c8bda20d5db> in run(self, corpora, reference_timelines)
     28         topic_to_preprocessed = {}
     29         for t in topics:
---> 30             topic_to_preprocessed[t] = self.preprocess(t, corpora[t])
     31 
     32         for t in topics:

~/nlp/lib/python3.5/site-packages/tilse/models/submodular/submodular.py in preprocess(self, topic_name, corpus)
    233 
    234         logging.info("Compute sentence similarities")
--> 235         sims = self.sentence_representation_computer(corpus).compute_pairwise_similarities()
    236 
    237         logging.info("Cluster sentence representations")

~/nlp/lib/python3.5/site-packages/tilse/representations/sentence_representations.py in compute_pairwise_similarities(self)
    216         sents, sents_vec = self._get_sents_with_representations()
    217 
--> 218         sims = 1 - metrics.pairwise.pairwise_distances(sents_vec, metric="cosine")
    219 
    220         for i, sent_a in enumerate(sents):

~/nlp/lib/python3.5/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, **kwds)
   1238         func = partial(distance.cdist, metric=metric, **kwds)
   1239 
-> 1240     return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1241 
   1242 

~/nlp/lib/python3.5/site-packages/sklearn/metrics/pairwise.py in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1081     if n_jobs == 1:
   1082         # Special case to avoid picklability checks in delayed
-> 1083         return func(X, Y, **kwds)
   1084 
   1085     # TODO: in some cases, backend='threading' may be appropriate

~/nlp/lib/python3.5/site-packages/sklearn/metrics/pairwise.py in cosine_distances(X, Y)
    568     """
    569     # 1.0 - cosine_similarity(X, Y) without copy
--> 570     S = cosine_similarity(X, Y)
    571     S *= -1
    572     S += 1

~/nlp/lib/python3.5/site-packages/sklearn/metrics/pairwise.py in cosine_similarity(X, Y, dense_output)
    908     # to avoid recursive import
    909 
--> 910     X, Y = check_pairwise_arrays(X, Y)
    911 
    912     X_normalized = normalize(X, copy=True)

~/nlp/lib/python3.5/site-packages/sklearn/metrics/pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype)
    104     if Y is X or Y is None:
    105         X = Y = check_array(X, accept_sparse='csr', dtype=dtype,
--> 106                             warn_on_dtype=warn_on_dtype, estimator=estimator)
    107     else:
    108         X = check_array(X, accept_sparse='csr', dtype=dtype,

~/nlp/lib/python3.5/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    422                              " a minimum of %d is required%s."
    423                              % (n_features, shape_repr, ensure_min_features,
--> 424                                 context))
    425 
    426     if warn_on_dtype and dtype_orig is not None and array.dtype != dtype_orig:

ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by check_pairwise_arrays.
```

Do you need some specific library to do preprocessing (probably mine is not done correctly). 

PS. I'm reproducing again the preprocessing to show you some of the warninigs (I'll post them here when finished).

**EDIT:**

Here I report some warning (again, not sure if they are affecting the computation or are somehow related to the errors):

```
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date 2013-7-19T9:27:42
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date 2013-W29
WARNING:tilse.data.documents:Could not parse date 199
WARNING:tilse.data.documents:Could not parse date 199X
WARNING:tilse.data.documents:Could not parse date 199
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date 198
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date 199
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date 2013-W26
WARNING:tilse.data.documents:Could not parse date 2013-W29
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date 2013-SU
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date 2013-W29
WARNING:tilse.data.documents:Could not parse date 199
WARNING:tilse.data.documents:Could not parse date 199X
WARNING:tilse.data.documents:Could not parse date 199
WARNING:tilse.data.documents:Could not parse date PAST_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
WARNING:tilse.data.documents:Could not parse date 2013-SP
WARNING:tilse.data.documents:Could not parse date PRESENT_REF
```

**Comment by smartschat** [comment] 2020-03-23 08:26
The warnings are not related to the errors, they just mean that not all dates output by the date parser were processed by tilse (which is expected).

The error suggests that linguistic preprocessing failed. Maybe there is an issue regarding the interplay of tilse with the current spaCy version. Could you post the versions of the libraries used? Which spaCy model did you install?

**Comment by MorenoLaQuatra** [comment] 2020-03-23 21:10
The results given by `pip freeze` command are reported below:

```
absl-py==0.7.0
altgraph==0.10.2
appdirs==1.4.3
asn1crypto==0.24.0
astor==0.7.1
backcall==0.1.0
backports-abc==0.5
bdist-mpkg==0.5.0
beautifulsoup4==4.5.3
bert-extractive-summarizer==0.2.0
bleach==3.1.0
blis==0.4.1
boto==2.45.0
boto3==1.9.92
botocore==1.12.92
breadability==0.1.20
bz2file==0.98
cachetools==4.0.0
catalogue==1.0.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.3
Click==7.0
cryptography==2.5
cycler==0.10.0
cymem==2.0.2
Cython==0.25.2
cytoolz==0.9.0.1
datasketch==1.4.1
de-core-news-sm==2.0.0
decorator==4.3.2
defusedxml==0.5.0
dill==0.2.6
docopt==0.6.2
docutils==0.14
elsapy==0.5.0
en-core-web-sm==2.1.0
entrypoints==0.3
es-core-news-sm==2.0.0
fasttext==0.8.3
fr-core-news-sm==2.0.0
ftfy==4.4.3
funcsigs==1.0.2
future==0.17.1
gast==0.2.2
gensim==3.7.1
graphviz==0.10.1
grpcio==1.18.0
h5py==2.9.0
html5lib==1.0.1
idna==2.8
ijson==2.6.1
importlib-metadata==1.5.0
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
it-core-news-sm==2.0.0
jedi==0.13.2
jellyfish==0.6.1
Jinja2==2.10
jmespath==0.9.3
joblib==0.14.1
JPype1==0.7.2
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterthemes==0.20.0
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
lesscpy==0.13.0
lexrank==0.1.0
llvmlite==0.31.0
lxml==3.8.0
macholib==1.5.1
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mistune==0.8.4
mock==2.0.0
modulegraph==0.10.4
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==1.0.2
nbconvert==5.4.1
nbformat==4.4.0
neo4jrestclient==2.1.1
networkx==2.2
neuralcoref==4.0
nl-core-news-sm==2.0.0
nltk==3.2.2
nose==1.3.7
notebook==5.7.4
numba==0.47.0
numpy==1.16.1
pandas==0.19.2
pandocfilters==1.4.2
parso==0.3.4
path.py==11.5.0
pathlib2==2.3.5
pbr==1.10.0
pexpect==4.6.0
pickleshare==0.7.5
plac==0.9.6
ply==3.11
preshed==3.0.2
prometheus-client==0.5.0
prompt-toolkit==2.0.8
protobuf==3.2.0
pt-core-news-sm==2.0.0
ptyprocess==0.6.0
py-rouge==1.1
py2app==0.7.3
pycparser==2.19
pyemd==0.5.1
Pygments==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.0.1
Pyphen==0.9.5
pyrsistent==0.14.11
pytextrank==1.1.0
python-dateutil==2.8.0
python-Levenshtein==0.12.0
pytz==2013.7
pyzmq==17.1.2
redis==3.2.0
regex==2018.1.10
requests==2.21.0
s3transfer==0.2.0
sacremoses==0.0.35
scikit-learn==0.18.1
scipy==1.2.1
seaborn==0.9.0
Send2Trash==1.5.0
sent2vec==0.0.0
sentence-transformers==0.2.5.1
sentencepiece==0.1.83
singledispatch==3.4.0.3
six==1.10.0
smart-open==1.8.0
spacy==2.2.4
spark-parser==1.8.7
spotlight==0.2.3
srsly==1.0.2
statistics==1.0.3.5
summa==1.2.0
sumy==0.6.0
tensorboard==1.12.2
tensorflow==0.12.1
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
textacy==0.6.0
thinc==7.4.0
tilse==0.2.1
toolz==0.9.0
torch==1.4.0
tornado==4.4.2
tqdm==4.43.0
traitlets==4.3.2
transformers==2.3.0
ujson==1.35
uncompyle6==3.2.5
Unidecode==1.1.1
uritools==2.2.0
urlextract==0.9
urllib3==1.24.1
virtualenv==15.1.0
wasabi==0.6.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wrapt==1.10.11
xdis==3.8.9
xlrd==1.2.0
xx-ent-wiki-sm==2.0.0
zipp==1.2.0
zope.interface==4.1.1
```

The installed spacy model is `en-core-web-sm-2.1.0`.

**Comment by MorenoLaQuatra** [comment] 2020-03-23 21:12
The relevant libraries given by `pip freeze` command are reported below:

```
en-core-web-sm==2.1.0
spacy==2.2.4
tilse==0.2.1
```

**Comment by smartschat** [comment] 2020-03-27 15:53
Thanks! I'll try to reproduce the error and will get back to you (this might take a few days).

**Comment by smartschat** [comment] 2020-04-11 21:10
I could reproduce the error. In the new spaCy versions, uppercase/lowercase behavior of lemmas was changed slightly, which screwed up tilse's sentence keyword filtering for some topics and led to the error you described.

The bug should be fixed in the version that is currently in the repository, could you clone and try?

**Comment by arianpasquali** [comment] 2020-04-23 19:34
Thank you @smartschat . I will re-run the experiments with your Random baseline.

**Comment by MorenoLaQuatra** [comment] 2020-05-09 15:50
Hi Sebastian, sorry if the answer took too long but I had problem in finding the right machine to reproduce the results. However now everything works, thanks for the quick response.

**Comment by arianpasquali** [comment] 2020-05-10 18:04
Here are the results with the new random baseline.
@MorenoLaQuatra 
https://docs.google.com/spreadsheets/d/1MK7rlCcFEMBeGHqL9p8MFJdZqIwqG0lstJtayqhLhE4/edit?usp=sharing

For content selection we can see that random selection is worst than the proposed methods, but I can't say the same for date selection.

**Comment by smartschat** [comment] 2020-05-10 19:43
@MorenoLaQuatra Great!

@arianpasquali Thank you for running the experiments! The results show that with sufficient temporal constraints and with pre-filtering sentences according to keywords, random selection is a very competitive baseline. Overall it performs quite similar to the regression model. The more temporally refined models still outperform it with regard to date selection.

These results are not in the paper (and the implementation was originally not in this repository) as I never applied the random baseline in the comparisons reported in the paper, I only used it initially for developing/validating the metrics. 

However, these are important results, so thank you again for asking and for running the experiments.

**Comment by MorenoLaQuatra** [comment] 2020-05-11 07:37
Thank you @arianpasquali  for sharing results, actually I got different kind of results, what are the *_spacy versions referring to?

**Comment by smartschat** [comment] 2020-05-11 10:47
@MorenoLaQuatra Can you share or send me your results?

**Comment by MorenoLaQuatra** [comment] 2020-05-11 10:53
Sure, those are the results I got for Timeline17 https://docs.google.com/spreadsheets/d/1lL3vt8gOIGT9SDUBbQuM1QBDl9y7s_LKr8oQg-5nP30

**Comment by smartschat** [comment] 2020-05-11 11:19
Thanks! From a rough look the trends are similar, but the numbers are different.

@arianpasquali @MorenoLaQuatra I'll investigate the differences, but this may take some time.

**Comment by arianpasquali** [comment] 2020-05-13 18:02
> Thank you @arianpasquali for sharing results, actually I got different kind of results, what are the *_spacy versions referring to?
@MorenoLaQuatra 

I am using spacy sentence representation. as you can see here https://github.com/smartschat/tilse/blob/master/tilse/representations/sentence_representations.py#L76

**Comment by MorenoLaQuatra** [comment] 2020-05-13 18:49
Oh I see. Thanks for the explanation.

**Comment by smartschat** [comment] 2020-05-22 15:49
When running a fresh installation of tilse, I could obtain results similar to the results posted by @MorenoLaQuatra. 

I suspected that differences in preprocessing could lead to changes in numbers. Therefore, I downgraded most packages/models to versions I used for the CoNLL '18 paper and re-ran the experiments. The results are very close to the numbers reported in the CoNLL '18 paper and are available here: https://docs.google.com/spreadsheets/d/1-JbyqAVzax_23YEKBEdjulsPXSjS0tQuOkYiZa3_MsM/edit?usp=sharing

I downgraded packages as follows (also needs Python 3.7 because of scikit-learn 0.20.0): 

```
spacy==2.0.12
en-core-web-sm==2.0.0
scikit-learn==0.20.0
textacy==0.6.2
```

It would be great if you could check whether you can reproduce these results.

I'll try to have a closer look at the actual differences in preprocessing, but this will take at least some weeks due to other commitments.

**Comment by MorenoLaQuatra** [comment] 2020-05-22 18:45
Thank you so much for your efforts @smartschat . I'll test out with downgraded packages and Python 3.7 .

**Comment by arianpasquali** [comment] 2020-06-03 10:49
@smartschat I am trying to run my experiments again using the versions you mentioned. However I found an error when trying to reproduce chieu method. There is an error with numba dependency and I assume I am using the wrong version.

I am using `numba==0.46.0`

I opened a new issues here https://github.com/smartschat/tilse/issues/2 since it is a different topic.

**Comment by smartschat** [comment] 2022-04-02 19:07
I'm closing this since (i) the random baseline is implemented now and (ii) there was no further activity regarding reproducibility, so I assume you were succesful in reproducing the results. Please open another issue if you have any reproducibility problems.

**Closed as completed by smartschat** 2022-04-02 19:07 UTC
